# Generated by Django 2.1.4 on 2020-04-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0017_auto_20200409_1527'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='my_subscribed_magazine',
            field=models.ManyToManyField(blank=True, null=True, to='magazine.Magazines'),
        ),
    ]
