# Generated by Django 2.1.4 on 2020-04-10 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermodel_my_subscribed_magazine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=55)),
                ('act_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserModel')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.CharField(choices=[('LK', 'Someone Liked Your Cast .'), ('VC', 'Someone Viewed Your Cast .'), ('VM', 'Someone Commented On Your Cast .'), ('SM', 'Someone Subscribed Your Magazine .'), ('LA', 'Latest Activity From Your Channel .')], max_length=20)),
                ('notify_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserModel')),
            ],
        ),
    ]
