# Generated by Django 2.1.4 on 2020-04-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activity_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(choices=[('LK', 'You Liked Someone"s WebCast .'), ('VC', 'You Viewed Someone"s WebCast .'), ('VM', 'You Commented On Someone"s WebCast .'), ('SM', 'You Subscribed Someone"s Magazine .'), ('LA', 'You Created a New WebCast .')], max_length=55),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notify',
            field=models.CharField(choices=[('LK', 'Someone Liked Your WebCast .'), ('VC', 'Someone Viewed Your WebCast .'), ('VM', 'Someone Commented On Your WebCast .'), ('SM', 'Someone Subscribed Your Magazine .'), ('LA', 'New Cast From Your SubScribed Magazine .')], max_length=20),
        ),
    ]
