# Generated by Django 2.1.4 on 2020-04-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200409_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notify',
            field=models.CharField(choices=[('Someone Liked Your WebCast .', 'LK'), ('Someone Viewed Your WebCast .', 'VC'), ('Someone Commented On Your WebCast .', 'VM'), ('Someone Subscribed Your Magazine .', 'SM'), ('New Cast From Your SubScribed Magazine .', 'LA')], max_length=40),
        ),
    ]
