# Generated by Django 2.1.4 on 2020-04-06 09:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.DateTimeField(default=datetime.datetime(2020, 4, 5, 23, 4, 17, 633361))),
                ('title', models.CharField(max_length=40)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pos', models.BooleanField(default=True)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserModel')),
            ],
        ),
        migrations.CreateModel(
            name='Magazines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subscribers', models.PositiveIntegerField(default=0)),
                ('is_monetize', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserModel')),
            ],
        ),
        migrations.AddField(
            model_name='casts',
            name='magazine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.Magazines'),
        ),
    ]
