# Generated by Django 2.1.4 on 2020-04-06 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 23, 11, 39, 587430)),
        ),
        migrations.AlterField(
            model_name='casts',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
