# Generated by Django 2.1.4 on 2020-04-06 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20200405_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 23, 13, 4, 140094)),
        ),
        migrations.AlterField(
            model_name='casts',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
