# Generated by Django 2.1.4 on 2020-04-06 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_auto_20200406_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 12, 53, 24, 726508)),
        ),
    ]
