# Generated by Django 2.1.4 on 2020-04-06 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('magazine', '0005_auto_20200406_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 13, 9, 44, 976326)),
        ),
        migrations.RemoveField(
            model_name='casts',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='casts',
            name='upvotes',
            field=models.ManyToManyField(blank=True, to='accounts.UserModel', verbose_name='liked'),
        ),
    ]
