# Generated by Django 2.1.4 on 2020-04-07 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0011_auto_20200406_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 15, 41, 34, 178358)),
        ),
        migrations.AlterField(
            model_name='casts',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
