# Generated by Django 2.1.4 on 2020-04-09 05:02

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine', '0012_auto_20200406_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazines',
            name='subscribed_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='subscribed'),
        ),
        migrations.AlterField(
            model_name='casts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 19, 2, 29, 792941)),
        ),
    ]
