# Generated by Django 2.1.4 on 2020-04-10 00:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0013_auto_20200408_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commented_cast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.Casts'),
        ),
        migrations.AlterField(
            model_name='casts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 14, 29, 6, 81207)),
        ),
    ]
