# Generated by Django 2.1.4 on 2020-04-10 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0016_auto_20200409_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 15, 27, 46, 9901)),
        ),
    ]
