# Generated by Django 2.1.4 on 2020-04-10 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0018_auto_20200409_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazines',
            name='subscribers',
        ),
        migrations.AlterField(
            model_name='casts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 15, 47, 38, 636630)),
        ),
    ]
