# Generated by Django 2.1.4 on 2020-04-10 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0021_auto_20200409_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 16, 46, 39, 285274)),
        ),
    ]
