# Generated by Django 2.1.4 on 2020-04-10 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0023_auto_20200409_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='casts',
            name='time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='casts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 21, 1, 6, 600292)),
        ),
    ]
