# Generated by Django 2.1.4 on 2020-04-11 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0024_auto_20200409_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casts',
            name='pages',
        ),
        migrations.AddField(
            model_name='casts',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='casts',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='casts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 14, 40, 50, 378381)),
        ),
    ]
