# Generated by Django 2.1.4 on 2020-04-11 01:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0026_auto_20200410_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='cast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.Casts'),
        ),
        migrations.AlterField(
            model_name='casts',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 15, 57, 7, 94590)),
        ),
    ]
